### ISSUE TITLE
How to view rules

### ISSUE THREAD

**Issue by linonetwo** [awasthiabhijeet/Learning-From-Rules#1]
I want to view what those rules look like, how can I dump them? Thanks.

**Comment by awasthiabhijeet** [comment]
Hi,
Thanks for your interest in our work.
We will be adding the rules for different datasets soon.
For YouTube spam datasets, rules were obtained from [here](https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/01_spam_tutorial.py)

**Comment by linonetwo** [comment]
Thank you for sharing, I will try this lib to generate some rule for my project.

**Comment by linonetwo** [comment]
Oh, I misunderstood, it is not a framework to generate rules, it is using rules to tag dataset.
Seems there are only very few rules in that tutorial.

Looking forward to your opensource of rules!

**Comment by awasthiabhijeet** [comment]
Hi!
Rules for [TREC](https://github.com/awasthiabhijeet/Learning-From-Rules/blob/master/data/TREC/rule.txt), [SPAM](https://github.com/awasthiabhijeet/Learning-From-Rules/blob/master/data/SMS/rule.txt) and [MITR](https://github.com/awasthiabhijeet/Learning-From-Rules/blob/master/data/SMS/rule.txt) are now there in the data dir.

I also came accross [this code](https://github.com/greenelab/snorkeling/blob/master/playground/epilepsy/2.epilepsy-labeler.ipynb) which might be useful for you. However, I never used it.

Thanks! :)
