### ISSUE TITLE
U_processed.p missing for YouTube dataset

### ISSUE THREAD

**Issue by suiyengar** [awasthiabhijeet/Learning-From-Rules#3]
Can you please add U_processed.p used in the paper for the YouTube data set ?

**Comment by awasthiabhijeet** [comment]
Hi,
Thanks for your interest in our work.

You can find the data missing in the GitHub repo available [here](https://drive.google.com/file/d/1dWTUC_f0Ks-Hg4TtkHrwWy0RmzLMH-X1/view?usp=sharing). This is because of the large file sizes.
