### ISSUE TITLE
Can't get performance in the paper.

### ISSUE THREAD

**Issue by mrbeann** [awasthiabhijeet/Learning-From-Rules#4]
I run this code and get the result as follows,
![image](https://user-images.githubusercontent.com/9161747/90948233-1733e080-e46f-11ea-89e6-bf60441ea974.png)

It seems not same as the paper, Is there anything I missed?

Thank you!

**Comment by mrbeann** [comment]
![image](https://user-images.githubusercontent.com/9161747/90981777-860b5980-e595-11ea-8442-9facb447c481.png)

After some adjustment, the result is much like the paper, but still some differences.

**Comment by awasthiabhijeet** [comment]
Hi,
Thanks for your interest in our work.

It might be hard to reproduce the results exactly since the seed is not set.
However, the trends in the results should hopefully be consistent, particularly for the noisier datasets like TREC where the precision of rules is low and conflict among the rules is high.

**Comment by mrbeann** [comment]
Yeah, it's quite hard to reproduce it exactly. So, the inconsistent is due to the random seed, not other tricks?

**Comment by awasthiabhijeet** [comment]
Yes. This is why we have also reported std deviations in the paper, based on 10 independent runs for each experiment.
I should have fixed seeds while running the experiments for exact reproducibility.
I do not believe that there is any other factor involved apart from the random seeds.
Please let me know if you think there is any other factor involved.

**Comment by mrbeann** [comment]
Okay, I'll tell you if I find some. Thanks!
