### ISSUE TITLE
suggestions on search space of gamma and q

### ISSUE THREAD

**Issue by JieyuZ2** [awasthiabhijeet/Learning-From-Rules#5]
Hi,

If we want to do hyper-parameter search for the two primary parameters of implyloss, ie, weighting factor **gamma** and **q** for Generalized-XENT loss. Do you have any suggestions on the search space?

**Comment by awasthiabhijeet** [comment]
Hi @JieyuZ2 ,
I will need to search through my logs. Sorry for the late reply as I've been a little busy.
Let me

**Comment by awasthiabhijeet** [comment]
Hi @JieyuZ2 ,
I will need to search through my logs. Sorry for the late reply as I've been a little busy.
Let me get back before the coming Monday.

**Comment by awasthiabhijeet** [comment]
Hi @JieyuZ2 ,
`q` of the generalized-xent loss used along with ImplyLoss is hardcoded to 0.2. 
https://github.com/awasthiabhijeet/Learning-From-Rules/blob/217c2d3b0cdaec1b22bc498c4cd17c5262b3fd13/src/hls/hls_model.py#L415
Here, we want to keep q closer to 0 assuming that rule-firings that match the gold label are more likely to demonstrate the correct generalization of the rule. 

For gamma, we typically tried following values: (1e-3, 3e-3, 5e-3, 1e-2, 3e-2, 5e-2, ... , 0.1)

**Comment by JieyuZ2** [comment]
Thank you!
